[theme]
primaryColor="#04045c"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f1f2f6"
textColor = "#38343c"
font="sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = false
maxMessageSize = 1000
